[pytest]
pythonpath = .src
asyncio_mode = auto
asyncio_default_fixture_loop_scope = session
asyncio_default_test_loop_scope = session

env =
    TEST_ENV=CONTAINER
    APP_CONFIG__ENV=TEST
    APP_CONFIG__STORAGE__S3__BUCKET=test-bucket
    APP_CONFIG__STORAGE__S3__SECURE=false
    APP_CONFIG__DB__DATABASE=test-db-boilerplate
; env_override_existing_values = 1


python_files = *_test.py *_tests.py test_*.py